# Generated by Django 3.2 on 2021-08-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_percent_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcode',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Code Discount'),
        ),
        migrations.AlterField(
            model_name='percentcode',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Code Discount'),
        ),
    ]
