# Generated by Django 3.2 on 2021-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20210819_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcode',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Code Discount'),
        ),
        migrations.AlterField(
            model_name='percentcode',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Code Discount'),
        ),
    ]
