# Generated by Django 3.2 on 2021-08-21 15:17

from django.db import migrations, models
import lib.rename_files


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='one.jpg', null=True, upload_to=lib.rename_files.rename_profile, verbose_name='Avatar'),
        ),
    ]
