# Generated by Django 3.2.5 on 2021-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecentedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cash_discount',
            field=models.ManyToManyField(to='order.CashDiscount'),
        ),
        migrations.AddField(
            model_name='product',
            name='precented_discount',
            field=models.ManyToManyField(to='order.PrecentedDiscount'),
        ),
    ]
