# Generated by Django 3.2.5 on 2021-08-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210811_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cash_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='cash_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cashdiscount'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='precented_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='precented_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.precenteddiscount'),
        ),
    ]
