# Generated by Django 3.2 on 2021-08-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_percent_percent'),
        ('order', '0005_auto_20210819_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='cash_discount',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='percent_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='cash_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discount.cashcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='percent_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discount.percentcode'),
        ),
    ]
