# Generated by Django 3.2 on 2021-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210819_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='price'),
        ),
    ]
