# Generated by Django 3.2 on 2021-08-17 22:06

from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import lib.rename_files
=======
import utils.rename_files
>>>>>>> 2e567137b12a8e3fc6bf62255974ab8998a032a4


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='author.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='BookObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='Inventory')),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True, verbose_name='Slug')),
<<<<<<< HEAD
                ('cover', models.ImageField(default='products/book_pictures/one.jpg', upload_to=lib.rename_files.rename_product_pic, verbose_name='cover')),
=======
                ('cover', models.ImageField(default='products/book_pictures/one.jpg', upload_to=utils.rename_files.rename_product_pic, verbose_name='cover')),
>>>>>>> 2e567137b12a8e3fc6bf62255974ab8998a032a4
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='products.book')),
            ],
            options={
                'verbose_name': 'Book Instance',
                'verbose_name_plural': 'Book Instances',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='products.Genre'),
        ),
    ]
