# Generated by Django 3.2 on 2021-08-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_percent_percent'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookobject',
            name='cash_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='discount.cash'),
        ),
        migrations.AddField(
            model_name='bookobject',
            name='percent_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='discount.percent'),
        ),
    ]
