# Generated by Django 3.2.6 on 2021-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210819_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Description'),
        ),
    ]
