# Generated by Django 3.2.6 on 2021-08-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
