# Generated by Django 3.2.6 on 2021-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Description'),
        ),
    ]
